version: '3'

services:
  javabox:
    build:
      context: .
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.ssh:/root/.ssh
      - ./config:$APP_ROOT/config
      - ./src:$APP_ROOT/src
      - idea_cache:/root/.IdeaIC2018.5
      - java_cache:/root/.java
    working_dir: $APP_ROOT
    command: /usr/share/intellij/bin/idea.sh

volumes:
  idea_cache:
  java_cache:
