version: '3'

services:
  javabox:
    container_name: sandbox
    build:
      context: .
      dockerfile: Dockerfile-javabox
    environment:
      - DISPLAY=$DISPLAY
      - PROJECTS=$PROJECTS
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ./config:$APP_ROOT/config
      - $PROJECTS:/root/projects
      - idea_cache:/root/.IdeaIC2018.5
      - java_cache:/root/.java
    working_dir: $APP_ROOT
    command: /usr/share/intellij/bin/idea.sh

volumes:
  idea_cache:  
  java_cache:  