version: '3'
services:
  intellij:
    build:
      context: .
      dockerfile: intellij/Dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config:$APP_ROOT/config
      - ./src:$APP_ROOT/src
      - idea_cache:/root/.IdeaIC2017.3
      - java_cache:/root/.java
    working_dir: $APP_ROOT
    command: /usr/share/intellij/bin/idea.sh
volumes:
  idea_cache:
  java_cache:
