version: '3'

services:
  intellij:
    build:
      context: .
      dockerfile: intellij/Dockerfile
    links:
      - scala
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config:$APP_ROOT/config
      - ./src:$APP_ROOT/src
      - idea_cache:/root/.IdeaIC2018.5
      - java_cache:/root/.java
    working_dir: $APP_ROOT
    command: /usr/share/intellij/bin/idea.sh

  scala:
    build:
      context: .
      dockerfile: scala/Dockerfile
    working_dir: $APP_ROOT
    command: sbt sbt-version

volumes:
  idea_cache:
  java_cache:
